export const LOGIN = 'LOGIN';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';

export const GET_PENJUALAN_STORE = 'GET_PENJUALAN_STORE';
export const GET_PENJUALAN_STORE_SUCCESS = 'GET_PENJUALAN_STORE_SUCCESS';
export const GET_PENJUALAN_STORE_FAIL = 'GET_PENJUALAN_STORE_FAIL';

export const GET_PENJUALAN_OFFICE = 'GET_PENJUALAN_OFFICE';
export const GET_PENJUALAN_OFFICE_SUCCESS = 'GET_PENJUALAN_OFFICE_SUCCESS';
export const GET_PENJUALAN_OFFICE_FAIL = 'GET_PENJUALAN_OFFICE_FAIL';

export const GET_PELANGGAN = 'GET_PELANGGAN';
export const GET_PELANGGAN_SUCCESS = 'GET_PELANGGAN_SUCCESS';
export const GET_PELANGGAN_FAIL = 'GET_PELANGGAN_FAIL';

export const GET_KARYAWAN = 'GET_KARYAWAN';
export const GET_KARYAWAN_SUCCESS = 'GET_KARYAWAN_SUCCESS';
export const GET_KARYAWAN_FAIL = 'GET_KARYAWAN_FAIL';

export const POST_KARYAWAN = 'POST_KARYAWAN';
export const POST_KARYAWAN_SUCCESS = 'POST_KARYAWAN_SUCCESS';
export const POST_KARYAWAN_FAIL = 'POST_KARYAWAN_FAIL';

export const DELETE_KARYAWAN = 'DELETE_KARYAWAN';
export const DELETE_KARYAWAN_SUCCESS = 'DELETE_KARYAWAN_SUCCESS';
export const DELETE_KARYAWAN_FAIL = 'DELETE_KARYAWAN_FAIL';

export const SEARCH_KARYAWAN = 'SEARCH_KARYAWAN';
export const SEARCH_KARYAWAN_SUCCESS = 'SEARCH_KARYAWAN_SUCCESS';
export const SEARCH_KARYAWAN_FAIL = 'SEARCH_KARYAWAN_FAIL';

export const UPDATE_KARYAWAN = 'UPDATE_KARYAWAN';
export const UPDATE_KARYAWAN_SUCCESS = 'UPDATE_KARYAWAN_SUCCESS';
export const UPDATE_KARYAWAN_FAIL = 'UPDATE_KARYAWAN_FAIL';

export const POST_PELANGGAN = 'POST_PELANGGAN';
export const POST_PELANGGAN_SUCCESS = 'POST_PELANGGAN_SUCCESS';
export const POST_PELANGGAN_FAIL = 'POST_PELANGGAN_FAIL';

export const POST_PENJUALAN_OFFICE = 'POST_PENJUALAN_OFFICE';
export const POST_PENJUALAN_OFFICE_SUCCESS = 'POST_PENJUALAN_OFFICE_SUCCESS';
export const POST_PENJUALAN_OFFICE_FAIL = 'POST_PENJUALAN_OFFICE_FAIL';

export const GET_DETAIL_PENJUALAN_STORE = 'GET_DETAIL_PENJUALAN_STORE';
export const GET_DETAIL_PENJUALAN_STORE_SUCCESS = 'GET_DETAIL_PENJUALAN_STORE_SUCCESS';
export const GET_DETAIL_PENJUALAN_STORE_FAIL = 'GET_DETAIL_PENJUALAN_STORE_FAIL';

export const GET_DETAIL_PENJUALAN_OFFICE = 'GET_DETAIL_PENJUALAN_OFFICE';
export const GET_DETAIL_PENJUALAN_OFFICE_SUCCESS = 'GET_DETAIL_PENJUALAN_OFFICE_SUCCESS';
export const GET_DETAIL_PENJUALAN_OFFICE_FAIL = 'GET_DETAIL_PENJUALAN_OFFICE_FAIL';

export const GET_BARANG_MASUK = 'GET_BARANG_MASUK';
export const GET_BARANG_MASUK_SUCCESS = 'GET_BARANG_MASUK_SUCCESS';
export const GET_BARANG_MASUK_FAIL = 'GET_BARANG_MASUK_FAIL';

export const GET_BARANG_KELUAR = 'GET_BARANG_KELUAR';
export const GET_BARANG_KELUAR_SUCCESS = 'GET_BARANG_KELUAR_SUCCESS';
export const GET_BARANG_KELUAR_FAIL = 'GET_BARANG_KELUAR_FAIL';

export const GET_STOCK_OPNAME = 'GET_STOCK_OPNAME';
export const GET_STOCK_OPNAME_SUCCESS = 'GET_STOCK_OPNAME_SUCCESS';
export const GET_STOCK_OPNAME_FAIL = 'GET_STOCK_OPNAME_FAIL';

export const GET_PEMBELIAN = 'GET_PEMBELIAN';
export const GET_PEMBELIAN_SUCCESS = 'GET_PEMBELIAN_SUCCESS';
export const GET_PEMBELIAN_FAIL = 'GET_PEMBELIAN_FAIL';

export const DELETE_PEMBELIAN = 'DELETE_PEMBELIAN';
export const DELETE_PEMBELIAN_SUCCESS = 'DELETE_PEMBELIAN_SUCCESS';
export const DELETE_PEMBELIAN_FAIL = 'DELETE_PEMBELIAN_FAIL';

export const GET_ALL_KATEGORI = 'GET_ALL_KATEGORI';
export const GET_ALL_KATEGORI_SUCCESS = 'GET_ALL_KATEGORI_SUCCESS';
export const GET_ALL_KATEGORI_FAIL = 'GET_ALL_KATEGORI_FAIL';

export const POST_KATEGORI = 'POST_KATEGORI';
export const POST_KATEGORI_SUCCESS = 'POST_KATEGORI_SUCCESS';
export const POST_KATEGORI_FAIL = 'POST_KATEGORI_FAIL';

export const GET_PEMASOK = 'GET_PEMASOK';
export const GET_PEMASOK_SUCCESS = 'GET_PEMASOK_SUCCESS';
export const GET_PEMASOK_FAIL = 'GET_PEMASOK_FAIL';

export const POST_PEMASOK = 'POST_PEMASOK';
export const POST_PEMASOK_SUCCESS = 'POST_PEMASOK_SUCCESS';
export const POST_PEMASOK_FAIL = 'POST_PEMASOK_FAIL';

export const GET_DETAIL_PESANAN = 'GET_DETAIL_PESANAN';
export const GET_DETAIL_PESANAN_SUCCESS = 'GET_DETAIL_PESANAN_SUCCESS';
export const GET_DETAIL_PESANAN_FAIL = 'GET_DETAIL_PESANAN_FAIL';

export const DASHBOARD_BIAYA = 'DASHBOARD_BIAYA';
export const DASHBOARD_BIAYA_SUCCESS = 'DASHBOARD_BIAYA_SUCCESS';
export const DASHBOARD_BIAYA_FAIL = 'DASHBOARD_BIAYA_FAIL';

export const DASHBOARD_BIAYA_PEMBELIAN = 'DASHBOARD_BIAYA_PEMBELIAN';
export const DASHBOARD_BIAYA_PEMBELIAN_SUCCESS = 'DASHBOARD_BIAYA_PEMBELIAN_SUCCESS';
export const DASHBOARD_BIAYA_PEMBELIAN_FAIL = 'DASHBOARD_BIAYA_PEMBELIAN_FAIL';

export const DASHBOARD_BIAYA_JUMLAH_CUSTOMER = 'DASHBOARD_BIAYA_JUMLAH_CUSTOMER';
export const DASHBOARD_BIAYA_JUMLAH_CUSTOMER_SUCCESS = 'DASHBOARD_BIAYA_JUMLAH_CUSTOMER_SUCCESS';
export const DASHBOARD_BIAYA_JUMLAH_CUSTOMER_FAIL = 'DASHBOARD_BIAYA_JUMLAH_CUSTOMER_FAIL';

export const DASHBOARD_BIAYA_JUMLAH_PRODUCT = 'DASHBOARD_BIAYA_JUMLAH_PRODUCT';
export const DASHBOARD_BIAYA_JUMLAH_PRODUCT_SUCCESS = 'DASHBOARD_BIAYA_JUMLAH_PRODUCT_SUCCESS';
export const DASHBOARD_BIAYA_JUMLAH_PRODUCT_FAIL = 'DASHBOARD_BIAYA_JUMLAH_PRODUCT_FAIL';

export const DASHBOARD_BIAYA_JUMLAH_SUPPLIER = 'DASHBOARD_BIAYA_JUMLAH_SUPPLIER';
export const DASHBOARD_BIAYA_JUMLAH_SUPPLIER_SUCCESS = 'DASHBOARD_BIAYA_JUMLAH_SUPPLIER_SUCCESS';
export const DASHBOARD_BIAYA_JUMLAH_SUPPLIER_FAIL = 'DASHBOARD_BIAYA_JUMLAH_SUPPLIER_FAIL';

export const DASHBOARD_KEUNTUNGAN = 'DASHBOARD_KEUNTUNGAN';
export const DASHBOARD_KEUNTUNGAN_SUCCESS = 'DASHBOARD_KEUNTUNGAN_SUCCESS';
export const DASHBOARD_KEUNTUNGAN_FAIL = 'DASHBOARD_KEUNTUNGAN_FAIL';

export const DASHBOARD_PEMBELIAN = 'DASHBOARD_PEMBELIAN';
export const DASHBOARD_PEMBELIAN_SUCCESS = 'DASHBOARD_PEMBELIAN_SUCCESS';
export const DASHBOARD_PEMBELIAN_FAIL = 'DASHBOARD_PEMBELIAN_FAIL';

export const DASHBOARD_PENDAPATAN = 'DASHBOARD_PENDAPATAN';
export const DASHBOARD_PENDAPATAN_SUCCESS = 'DASHBOARD_PENDAPATAN_SUCCESS';
export const DASHBOARD_PENDAPATAN_FAIL = 'DASHBOARD_PENDAPATAN_FAIL';

export const DASHBOARD_PENJUALAN = 'DASHBOARD_PENJUALAN';
export const DASHBOARD_PENJUALAN_SUCCESS = 'DASHBOARD_PENJUALAN_SUCCESS';
export const DASHBOARD_PENJUALAN_FAIL = 'DASHBOARD_PENJUALAN_FAIL';

export const DASHBOARD_STOCK_OFFICE = 'DASHBOARD_STOCK_OFFICE';
export const DASHBOARD_STOCK_OFFICE_SUCCESS = 'DASHBOARD_STOCK_OFFICE_SUCCESS';
export const DASHBOARD_STOCK_OFFICE_FAIL = 'DASHBOARD_STOCK_OFFICE_FAIL';

export const DASHBOARD_STOCK_STORE = 'DASHBOARD_STOCK_STORE';
export const DASHBOARD_STOCK_STORE_SUCCESS = 'DASHBOARD_STOCK_STORE_SUCCESS';
export const DASHBOARD_STOCK_STORE_FAIL = 'DASHBOARD_STOCK_STORE_FAIL';

export const ADD_MASTER_PROJECT = 'ADD_MASTER_PROJECT';
export const ADD_MASTER_PROJECT_SUCCESS = 'ADD_MASTER_PROJECT_SUCCESS';
export const ADD_MASTER_PROJECT_FAIL = 'ADD_MASTER_PROJECT_FAIL';

export const GET_MASTER_PROJECT = 'GET_MASTER_PROJECT';
export const GET_MASTER_PROJECT_SUCCESS = 'GET_MASTER_PROJECT_SUCCESS';
export const GET_MASTER_PROJECT_FAIL = 'GET_MASTER_PROJECT_FAIL';

export const DELETE_MASTER_PROJECT = 'DELETE_MASTER_PROJECT';
export const DELETE_MASTER_PROJECT_SUCCESS = 'DELETE_MASTER_PROJECT_SUCCESS';
export const DELETE_MASTER_PROJECT_FAIL = 'DELETE_MASTER_PROJECT_FAIL';

export const POST_MASTER_PROJECT = 'POST_MASTER_PROJECT';
export const POST_MASTER_PROJECT_SUCCESS = 'POST_MASTER_PROJECT_SUCCESS';
export const POST_MASTER_PROJECT_FAIL = 'POST_MASTER_PROJECT_FAIL';

export const SEARCH_MASTER_PROJECT = 'SEARCH_MASTER_PROJECT';
export const SEARCH_MASTER_PROJECT_SUCCESS = 'SEARCH_MASTER_PROJECT_SUCCESS';
export const SEARCH_MASTER_PROJECT_FAIL = 'SEARCH_MASTER_PROJECT_FAIL';

export const UPDATE_MASTER_PROJECT = 'UPDATE_MASTER_PROJECT';
export const UPDATE_MASTER_PROJECT_SUCCESS = 'UPDATE_MASTER_PROJECT_SUCCESS';
export const UPDATE_MASTER_PROJECT_FAIL = 'UPDATE_MASTER_PROJECT_FAIL';

export const GET_MASTER_PRODUCT = 'GET_MASTER_PRODUCT';
export const GET_MASTER_PRODUCT_SUCCESS = 'GET_MASTER_PRODUCT_SUCCESS';
export const GET_MASTER_PRODUCT_FAIL = 'GET_MASTER_PRODUCT_FAIL';

export const UPDATE_MASTER_PRODUCT = 'UPDATE_MASTER_PRODUCT';
export const UPDATE_MASTER_PRODUCT_SUCCESS = 'UPDATE_MASTER_PRODUCT_SUCCESS';
export const UPDATE_MASTER_PRODUCT_FAIL = 'UPDATE_MASTER_PRODUCT_FAIL';

export const POST_MASTER_PRODUCT = 'POST_MASTER_PRODUCT';
export const POST_MASTER_PRODUCT_SUCCESS = 'POST_MASTER_PRODUCT_SUCCESS';
export const POST_MASTER_PRODUCT_FAIL = 'POST_MASTER_PRODUCT_FAIL';

export const SEARCH_MASTER_PRODUCT = 'SEARCH_MASTER_PRODUCT';
export const SEARCH_MASTER_PRODUCT_SUCCESS = 'SEARCH_MASTER_PRODUCT_SUCCESS';
export const SEARCH_MASTER_PRODUCT_FAIL = 'SEARCH_MASTER_PRODUCT_FAIL';

export const DELETE_MASTER_PRODUCT = 'DELETE_MASTER_PRODUCT';
export const DELETE_MASTER_PRODUCT_SUCCESS = 'DELETE_MASTER_PRODUCT_SUCCESS';
export const DELETE_MASTER_PRODUCT_FAIL = 'DELETE_MASTER_PRODUCT_FAIL';

export const DELETE_MASTER_TIPE = 'DELETE_MASTER_TIPE';
export const DELETE_MASTER_TIPE_SUCCESS = 'DELETE_MASTER_TIPE_SUCCESS';
export const DELETE_MASTER_TIPE_FAIL = 'DELETE_MASTER_TIPE_FAIL';

export const GET_MASTER_TIPE = 'GET_MASTER_TIPE';
export const GET_MASTER_TIPE_SUCCESS = 'GET_MASTER_TIPE_SUCCESS';
export const GET_MASTER_TIPE_FAIL = 'GET_MASTER_TIPE_FAIL';

export const POST_MASTER_TIPE = 'POST_MASTER_TIPE';
export const POST_MASTER_TIPE_SUCCESS = 'POST_MASTER_TIPE_SUCCESS';
export const POST_MASTER_TIPE_FAIL = 'POST_MASTER_TIPE_FAIL';

export const UPDATE_MASTER_TIPE = 'UPDATE_MASTER_TIPE';
export const UPDATE_MASTER_TIPE_SUCCESS = 'UPDATE_MASTER_TIPE_SUCCESS';
export const UPDATE_MASTER_TIPE_FAIL = 'UPDATE_MASTER_TIPE_FAIL';

export const SEARCH_MASTER_TIPE = 'SEARCH_MASTER_TIPE';
export const SEARCH_MASTER_TIPE_SUCCESS = 'SEARCH_MASTER_TIPE_SUCCESS';
export const SEARCH_MASTER_TIPE_FAIL = 'SEARCH_MASTER_TIPE_FAIL';

export const GET_MASTER_OFFICE = 'GET_MASTER_OFFICE';
export const GET_MASTER_OFFICE_SUCCESS = 'GET_MASTER_OFFICE_SUCCESS';
export const GET_MASTER_OFFICE_FAIL = 'GET_MASTER_OFFICE_FAIL';

export const POST_MASTER_OFFICE = 'POST_MASTER_OFFICE';
export const POST_MASTER_OFFICE_SUCCESS = 'POST_MASTER_OFFICE_SUCCESS';
export const POST_MASTER_OFFICE_FAIL = 'POST_MASTER_OFFICE_FAIL';

export const DELETE_MASTER_OFFICE = 'DELETE_MASTER_OFFICE';
export const DELETE_MASTER_OFFICE_SUCCESS = 'DELETE_MASTER_OFFICE_SUCCESS';
export const DELETE_MASTER_OFFICE_FAIL = 'DELETE_MASTER_OFFICE_FAIL';

export const UPDATE_MASTER_OFFICE = 'UPDATE_MASTER_OFFICE';
export const UPDATE_MASTER_OFFICE_SUCCESS = 'UPDATE_MASTER_OFFICE_SUCCESS';
export const UPDATE_MASTER_OFFICE_FAIL = 'UPDATE_MASTER_OFFICE_FAIL';

export const SEARCH_MASTER_OFFICE = 'SEARCH_MASTER_OFFICE';
export const SEARCH_MASTER_OFFICE_SUCCESS = 'SEARCH_MASTER_OFFICE_SUCCESS';
export const SEARCH_MASTER_OFFICE_FAIL = 'SEARCH_MASTER_OFFICE_FAIL';

export const ADD_MASTER_AKSESORIS = 'ADD_MASTER_AKSESORIS';
export const ADD_MASTER_AKSESORIS_SUCCESS = 'ADD_MASTER_AKSESORIS_SUCCESS';
export const ADD_MASTER_AKSESORIS_FAIL = 'ADD_MASTER_AKSESORIS_FAIL';

export const GET_MASTER_AKSESORIS = 'GET_MASTER_AKSESORIS';
export const GET_MASTER_AKSESORIS_SUCCESS = 'GET_MASTER_AKSESORIS_SUCCESS';
export const GET_MASTER_AKSESORIS_FAIL = 'GET_MASTER_AKSESORIS_FAIL';

export const DELETE_MASTER_AKSESORIS = 'DELETE_MASTER_AKSESORIS';
export const DELETE_MASTER_AKSESORIS_SUCCESS = 'DELETE_MASTER_AKSESORIS_SUCCESS';
export const DELETE_MASTER_AKSESORIS_FAIL = 'DELETE_MASTER_AKSESORIS_FAIL';

export const POST_MASTER_AKSESORIS = 'POST_MASTER_AKSESORIS';
export const POST_MASTER_AKSESORIS_SUCCESS = 'POST_MASTER_AKSESORIS_SUCCESS';
export const POST_MASTER_AKSESORIS_FAIL = 'POST_MASTER_AKSESORIS_FAIL';

export const SEARCH_MASTER_AKSESORIS = 'SEARCH_MASTER_AKSESORIS';
export const SEARCH_MASTER_AKSESORIS_SUCCESS = 'SEARCH_MASTER_AKSESORIS_SUCCESS';
export const SEARCH_MASTER_AKSESORIS_FAIL = 'SEARCH_MASTER_AKSESORIS_FAIL';

export const UPDATE_MASTER_AKSESORIS = 'UPDATE_MASTER_AKSESORIS';
export const UPDATE_MASTER_AKSESORIS_SUCCESS = 'UPDATE_MASTER_AKSESORIS_SUCCESS';
export const UPDATE_MASTER_AKSESORIS_FAIL = 'UPDATE_MASTER_AKSESORIS_FAIL';

export const ADD_MASTER_KATEGORI = 'ADD_MASTER_KATEGORI';
export const ADD_MASTER_KATEGORI_SUCCESS = 'ADD_MASTER_KATEGORI_SUCCESS';
export const ADD_MASTER_KATEGORI_FAIL = 'ADD_MASTER_KATEGORI_FAIL';

export const GET_MASTER_KATEGORI = 'GET_MASTER_KATEGORI';
export const GET_MASTER_KATEGORI_SUCCESS = 'GET_MASTER_KATEGORI_SUCCESS';
export const GET_MASTER_KATEGORI_FAIL = 'GET_MASTER_KATEGORI_FAIL';

export const DELETE_MASTER_KATEGORI = 'DELETE_MASTER_KATEGORI';
export const DELETE_MASTER_KATEGORI_SUCCESS = 'DELETE_MASTER_KATEGORI_SUCCESS';
export const DELETE_MASTER_KATEGORI_FAIL = 'DELETE_MASTER_KATEGORI_FAIL';

export const POST_MASTER_KATEGORI = 'POST_MASTER_KATEGORI';
export const POST_MASTER_KATEGORI_SUCCESS = 'POST_MASTER_KATEGORI_SUCCESS';
export const POST_MASTER_KATEGORI_FAIL = 'POST_MASTER_KATEGORI_FAIL';

export const SEARCH_MASTER_KATEGORI = 'SEARCH_MASTER_KATEGORI';
export const SEARCH_MASTER_KATEGORI_SUCCESS = 'SEARCH_MASTER_KATEGORI_SUCCESS';
export const SEARCH_MASTER_KATEGORI_FAIL = 'SEARCH_MASTER_KATEGORI_FAIL';

export const UPDATE_MASTER_KATEGORI = 'UPDATE_MASTER_KATEGORI';
export const UPDATE_MASTER_KATEGORI_SUCCESS = 'UPDATE_MASTER_KATEGORI_SUCCESS';
export const UPDATE_MASTER_KATEGORI_FAIL = 'UPDATE_MASTER_KATEGORI_FAIL';

export const ADD_MASTER_UKURAN = 'ADD_MASTER_UKURAN';
export const ADD_MASTER_UKURAN_SUCCESS = 'ADD_MASTER_UKURAN_SUCCESS';
export const ADD_MASTER_UKURAN_FAIL = 'ADD_MASTER_UKURAN_FAIL';

export const GET_MASTER_UKURAN = 'GET_MASTER_UKURAN';
export const GET_MASTER_UKURAN_SUCCESS = 'GET_MASTER_UKURAN_SUCCESS';
export const GET_MASTER_UKURAN_FAIL = 'GET_MASTER_UKURAN_FAIL';

export const DELETE_MASTER_UKURAN = 'DELETE_MASTER_UKURAN';
export const DELETE_MASTER_UKURAN_SUCCESS = 'DELETE_MASTER_UKURAN_SUCCESS';
export const DELETE_MASTER_UKURAN_FAIL = 'DELETE_MASTER_UKURAN_FAIL';

export const POST_MASTER_UKURAN = 'POST_MASTER_UKURAN';
export const POST_MASTER_UKURAN_SUCCESS = 'POST_MASTER_UKURAN_SUCCESS';
export const POST_MASTER_UKURAN_FAIL = 'POST_MASTER_UKURAN_FAIL';

export const SEARCH_MASTER_UKURAN = 'SEARCH_MASTER_UKURAN';
export const SEARCH_MASTER_UKURAN_SUCCESS = 'SEARCH_MASTER_UKURAN_SUCCESS';
export const SEARCH_MASTER_UKURAN_FAIL = 'SEARCH_MASTER_UKURAN_FAIL';

export const UPDATE_MASTER_UKURAN = 'UPDATE_MASTER_UKURAN';
export const UPDATE_MASTER_UKURAN_SUCCESS = 'UPDATE_MASTER_UKURAN_SUCCESS';
export const UPDATE_MASTER_UKURAN_FAIL = 'UPDATE_MASTER_UKURAN_FAIL';
