export const LOGIN = 'LOGIN';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';

export const GET_PENJUALAN_STORE = 'GET_PENJUALAN_STORE';
export const GET_PENJUALAN_STORE_SUCCESS = 'GET_PENJUALAN_STORE_SUCCESS';
export const GET_PENJUALAN_STORE_FAIL = 'GET_PENJUALAN_STORE_FAIL';

export const GET_PENJUALAN_OFFICE = 'GET_PENJUALAN_OFFICE';
export const GET_PENJUALAN_OFFICE_SUCCESS = 'GET_PENJUALAN_OFFICE_SUCCESS';
export const GET_PENJUALAN_OFFICE_FAIL = 'GET_PENJUALAN_OFFICE_FAIL';

export const GET_PELANGGAN = 'GET_PELANGGAN';
export const GET_PELANGGAN_SUCCESS = 'GET_PELANGGAN_SUCCESS';
export const GET_PELANGGAN_FAIL = 'GET_PELANGGAN_FAIL';

export const GET_KARYAWAN = 'GET_KARYAWAN';
export const GET_KARYAWAN_SUCCESS = 'GET_KARYAWAN_SUCCESS';
export const GET_KARYAWAN_FAIL = 'GET_KARYAWAN_FAIL';

export const POST_KARYAWAN = 'POST_KARYAWAN';
export const POST_KARYAWAN_SUCCESS = 'POST_KARYAWAN_SUCCESS';
export const POST_KARYAWAN_FAIL = 'POST_KARYAWAN_FAIL';

export const POST_PELANGGAN = 'POST_PELANGGAN';
export const POST_PELANGGAN_SUCCESS = 'POST_PELANGGAN_SUCCESS';
export const POST_PELANGGAN_FAIL = 'POST_PELANGGAN_FAIL';

export const POST_PENJUALAN_OFFICE = 'POST_PENJUALAN_OFFICE';
export const POST_PENJUALAN_OFFICE_SUCCESS = 'POST_PENJUALAN_OFFICE_SUCCESS';
export const POST_PENJUALAN_OFFICE_FAIL = 'POST_PENJUALAN_OFFICE_FAIL';

export const GET_DETAIL_PENJUALAN_STORE = 'GET_DETAIL_PENJUALAN_STORE';
export const GET_DETAIL_PENJUALAN_STORE_SUCCESS = 'GET_DETAIL_PENJUALAN_STORE_SUCCESS';
export const GET_DETAIL_PENJUALAN_STORE_FAIL = 'GET_DETAIL_PENJUALAN_STORE_FAIL';

export const GET_DETAIL_PENJUALAN_OFFICE = 'GET_DETAIL_PENJUALAN_OFFICE';
export const GET_DETAIL_PENJUALAN_OFFICE_SUCCESS = 'GET_DETAIL_PENJUALAN_OFFICE_SUCCESS';
export const GET_DETAIL_PENJUALAN_OFFICE_FAIL = 'GET_DETAIL_PENJUALAN_OFFICE_FAIL';

export const GET_BARANG_MASUK = 'GET_BARANG_MASUK';
export const GET_BARANG_MASUK_SUCCESS = 'GET_BARANG_MASUK_SUCCESS';
export const GET_BARANG_MASUK_FAIL = 'GET_BARANG_MASUK_FAIL';

export const GET_BARANG_KELUAR = 'GET_BARANG_KELUAR';
export const GET_BARANG_KELUAR_SUCCESS = 'GET_BARANG_KELUAR_SUCCESS';
export const GET_BARANG_KELUAR_FAIL = 'GET_BARANG_KELUAR_FAIL';

export const GET_STOCK_OPNAME = 'GET_STOCK_OPNAME';
export const GET_STOCK_OPNAME_SUCCESS = 'GET_STOCK_OPNAME_SUCCESS';
export const GET_STOCK_OPNAME_FAIL = 'GET_STOCK_OPNAME_FAIL';

export const GET_PEMBELIAN = 'GET_PEMBELIAN';
export const GET_PEMBELIAN_SUCCESS = 'GET_PEMBELIAN_SUCCESS';
export const GET_PEMBELIAN_FAIL = 'GET_PEMBELIAN_FAIL';

export const POST_PEMBELIAN = 'POST_PEMBELIAN';
export const POST_PEMBELIAN_SUCCESS = 'POST_PEMBELIAN_SUCCESS';
export const POST_PEMBELIAN_FAIL = 'POST_PEMBELIAN_FAIL';

export const GET_ALL_KATEGORI = 'GET_ALL_KATEGORI';
export const GET_ALL_KATEGORI_SUCCESS = 'GET_ALL_KATEGORI_SUCCESS';
export const GET_ALL_KATEGORI_FAIL = 'GET_ALL_KATEGORI_FAIL';

export const POST_KATEGORI = 'POST_KATEGORI';
export const POST_KATEGORI_SUCCESS = 'POST_KATEGORI_SUCCESS';
export const POST_KATEGORI_FAIL = 'POST_KATEGORI_FAIL';

export const GET_MASER_OFFICE = 'GET_MASER_OFFICE';
export const GET_MASER_OFFICE_SUCCESS = 'GET_MASER_OFFICE_SUCCESS';
export const GET_MASER_OFFICE_FAIL = 'GET_MASER_OFFICE_FAIL';

export const POST_MASER_OFFICE = 'POST_MASER_OFFICE';
export const POST_MASER_OFFICE_SUCCESS = 'POST_MASER_OFFICE_SUCCESS';
export const POST_MASER_OFFICE_FAIL = 'POST_MASER_OFFICE_FAIL';

export const POST_MASER_PROJECT = 'POST_MASER_PROJECT';
export const POST_MASER_PROJECT_SUCCESS = 'POST_MASER_PROJECT_SUCCESS';
export const POST_MASER_PROJECT_FAIL = 'POST_MASER_PROJECT_FAIL';

export const GET_MASER_PROJECT = 'GET_MASER_PROJECT';
export const GET_MASER_PROJECT_SUCCESS = 'GET_MASER_PROJECT_SUCCESS';
export const GET_MASER_PROJECT_FAIL = 'GET_MASER_PROJECT_FAIL';

export const GET_PEMASOK = 'GET_PEMASOK';
export const GET_PEMASOK_SUCCESS = 'GET_PEMASOK_SUCCESS';
export const GET_PEMASOK_FAIL = 'GET_PEMASOK_FAIL';

export const POST_PEMASOK = 'POST_PEMASOK';
export const POST_PEMASOK_SUCCESS = 'POST_PEMASOK_SUCCESS';
export const POST_PEMASOK_FAIL = 'POST_PEMASOK_FAIL';

export const GET_DETAIL_PESANAN = 'GET_DETAIL_PESANAN';
export const GET_DETAIL_PESANAN_SUCCESS = 'GET_DETAIL_PESANAN_SUCCESS';
export const GET_DETAIL_PESANAN_FAIL = 'GET_DETAIL_PESANAN_FAIL';

